services:
  router:
    image: itzg/mc-router:latest
    command: "-in-docker"
    container_name: mc_router
    restart: unless-stopped
    depends_on:
      - fische
      - flasche
    ports:
      - "25565:25565"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  fische:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    restart: unless-stopped
    labels:
      mc-router.host: "fische.alleaffengaffen.ch"
      mc-router.default: true
    container_name: fische
    environment:
      EULA: "TRUE"
      VERSION: "1.21"
      ALLOW_FLIGHT: 'TRUE'
      DIFFICULTY: 'normal'
      ENABLE_WHITELIST: 'TRUE'
      MAX_PLAYERS: '2'
      MEMORY: '8G'
      MODE: 'survival'
      MOTD: 'Fischers Fritz fischt frische Fische'
      OVERRIDE_WHITELIST: 'true'
      SERVER_NAME: 'fische'
      SIMULATION_DISTANCE: '10'
      SYNC_CHUNK_WRITES: 'FALSE'
      TYPE: 'VANILLA'
      USE_AIKAR_FLAGS: 'TRUE'
      VIEW_DISTANCE: '10'
      WHITELIST: 'technat,grosseklappe2,duffy_26'
      OPS: 'technat,duffy_26'
      ENABLE_COMMAND_BLOCK: 'TRUE'
      MODPACK_PLATFORM: 'MODRINTH'
      MODRINTH_MODPACK: '1ocGzRHv' # https://modrinth.com/modpack/vanilla-perfected
    volumes:
      - ./fische_data:/data
  backups-fische:
    image: itzg/mc-backup
    restart: unless-stopped
    environment:
      BACKUP_INTERVAL: "24h"
      RCON_HOST: fische
      PAUSE_IF_NO_PLAYERS: "true"
      BACKUP_METHOD: "restic"
      RESTIC_REPOSITORY: "swift:minecraft-backups:/fische"
    env_file:
      - .env
    volumes:
      - ./fische_data:/data:ro
  flasche:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    container_name: flasche
    restart: unless-stopped
    labels:
      mc-router.host: "flasche.alleaffengaffen.ch"
    environment:
      EULA: "TRUE"
      ALLOW_FLIGHT: 'TRUE'
      DIFFICULTY: 'easy'
      ENABLE_WHITELIST: 'TRUE'
      MAX_PLAYERS: '8'
      MEMORY: '8G'
      MODE: 'survival'
      MOTD: 'Ihr seid alles Flaschen'
      OVERRIDE_WHITELIST: 'true'
      SERVER_NAME: 'flasche'
      SIMULATION_DISTANCE: '10'
      SYNC_CHUNK_WRITES: 'FALSE'
      TYPE: 'VANILLA'
      USE_AIKAR_FLAGS: 'TRUE'
      VIEW_DISTANCE: '10'
      WHITELIST: "duundig,nbrac00,BEBEY00,DaveSkillerHD,schischkebab,Joscha_00,technat,duffy_26" 
      OPS: 'technat,duffy_26'
    volumes:
      - ./flasche_data:/data
  backups-flasche:
    image: itzg/mc-backup
    restart: unless-stopped
    environment:
      BACKUP_INTERVAL: "24h"
      RCON_HOST: flasche
      PAUSE_IF_NO_PLAYERS: "true"
      BACKUP_METHOD: "restic"
      RESTIC_REPOSITORY: "swift:minecraft-backups:/flasche"
    env_file:
      - .env
    volumes:
      - ./flasche_data:/data:ro