# fly.toml app configuration file generated for minecraft-flasche on 2024-12-27T11:20:33+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'minecraft-flasche'
primary_region = 'cdg'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]
  image = 'itzg/minecraft-server:latest'

[env]
  AUTOSTOP_TIMEOUT_EST = '60'
  AUTOSTOP_TIMEOUT_INIT = '300'
  AUTOSTOP_PKILL_USE_SUDO = "TRUE"
  DIFFICULTY = 'easy'
  ENABLE_AUTOSTOP = 'TRUE'
  EULA = 'TRUE'
  MAX_PLAYERS = '8'
  MEMORY = '2300M'
  MODE = 'survival'
  MOTD = 'Ihr seid alles Flaschen'
  PRIMARY_REGION = 'cdg'
  SERVER_NAME = 'flasche'
  SIMULATION_DISTANCE = '10'
  TYPE = 'VANILLA'
  USE_AIKAR_FLAGS = 'TRUE'
  VIEW_DISTANCE = '10'
  ENABLE_WHITELIST = 'TRUE'
  OVERRIDE_WHITELIST = 'true'
  WHITELIST= "duundig,nbrac00,BEBEY00,DaveSkillerHD,schischkebab,Joscha_00,technat" 
  OPS = 'technat'
  SYNC_CHUNK_WRITES = "FALSE"

[[mounts]]
  source = 'mc_server'
  destination = '/data'
  initial_size = '1gb'
  snapshot_retention = 14

[[services]]
  protocol = 'tcp'
  internal_port = 25565
  auto_stop_machines = "stop"
  auto_start_machines = false
  min_machines_running = 0

  [[services.ports]]
    port = 25565


[[vm]]
  size = 'shared-cpu-4x'
  memory = '3gb'
  cpu_kind = 'shared'
  cpus = 4
